language: node_js
node_js:
  - '8'
  - '6'
before_deploy:
  - npm install
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx lerna publish from-git --yes
    on:
      repo: revelrylabs/harmonium
      tags: true
      node: '8'
    skip_cleanup: true
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      repo: revelrylabs/harmonium
      node: '8'
